#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DOC="docs/RELEASE_CONTRACTS.md"
RUNBOOK="docs/RELEASE_TAG_ROLLBACK_RUNBOOK.md"
MATRIX="docs/RELEASE_SCRIPT_MATRIX.md"
test -f "$DOC"
test -f "$RUNBOOK"
test -f "$MATRIX"

rg -q --fixed-strings "# Release Contracts" "$DOC"
rg -q --fixed-strings "## Primary Entry Points" "$DOC"
rg -q --fixed-strings "## Contract Layers" "$DOC"
rg -q --fixed-strings "## When To Run Which Script" "$DOC"
rg -q --fixed-strings "## CI Guard" "$DOC"
rg -q --fixed-strings "Runtime contract note:" "$DOC"
rg -q --fixed-strings "## Operator Quick Order" "$DOC"
rg -q --fixed-strings "## Related References" "$DOC"
rg -q --fixed-strings "## Local Dirty-Worktree Quick Smoke" "$DOC"

rg -q --fixed-strings "scripts/check_release_contracts.sh" "$DOC"
rg -q --fixed-strings "scripts/check_release_docs_contracts.sh" "$DOC"
rg -q --fixed-strings "scripts/check_shell_health_contract.sh" "$DOC"
rg -q --fixed-strings "scripts/control_plane_smoke.sh" "$DOC"
rg -q --fixed-strings "scripts/wm_event_refresh_smoke.sh" "$DOC"
rg -q --fixed-strings "scripts/check_control_plane_docs_contract.sh" "$DOC"
rg -q --fixed-strings "scripts/check_release_validate_ci.sh" "$DOC"
rg -q --fixed-strings "scripts/check_shell_health_contract.sh" "$DOC"
rg -q --fixed-strings "scripts/control_plane_smoke.sh" "$DOC"
rg -q --fixed-strings "self-skip when unavailable" "$DOC"
rg -q --fixed-strings "scripts/check_release_contracts_contract.sh" "$DOC"
rg -q --fixed-strings "Release-validate contract summary:" "$DOC"
rg -q --fixed-strings "scripts/check_release_validate_contract.sh" "$DOC"
rg -q --fixed-strings "scripts/release_validate.sh --ci --require-clean" "$DOC"
rg -q --fixed-strings "scripts/check_release_contracts.sh --docs-only" "$DOC"
rg -q --fixed-strings "scripts/check_release_contracts.sh" "$DOC"
rg -q --fixed-strings "scripts/cut_release_tag.sh --version vX.Y.Z --apply --commit-notes --push" "$DOC"
rg -q --fixed-strings "scripts/publish_release_tag.sh --version vX.Y.Z --apply" "$DOC"
rg -q --fixed-strings "scripts/check_release_contracts.sh --docs-only" "$MATRIX"
rg -q --fixed-strings "scripts/release_validate.sh --ci --require-clean" "$MATRIX"
rg -q --fixed-strings "scripts/check_release_validate_ci.sh" "$MATRIX"
rg -q --fixed-strings "scripts/check_shell_health_contract.sh" "$MATRIX"
rg -q --fixed-strings "scripts/control_plane_smoke.sh" "$MATRIX"
rg -q --fixed-strings "scripts/wm_event_refresh_smoke.sh" "$MATRIX"
rg -q --fixed-strings "docs/RELEASE_TAG_ROLLBACK_RUNBOOK.md" "$DOC"
rg -q --fixed-strings "docs/RELEASE_SMOKE_MODES.md" "$DOC"
rg -q --fixed-strings "docs/RELEASE_VALIDATE_MODES.md" "$DOC"
rg -q --fixed-strings "RELEASE_VALIDATE_ALLOW_DIRTY=1 scripts/check_release_contracts.sh" "$DOC"
rg -q --fixed-strings "Local default recommendation:" "$DOC"
rg -q --fixed-strings 'start with `scripts/check_release_contracts.sh --docs-only`' "$DOC"
rg -q --fixed-strings "Do not use dirty-worktree override in CI or release cut/tag workflows." "$DOC"
rg -q --fixed-strings "scripts/release_validate.sh --ci --require-clean" "$DOC"
rg -q --fixed-strings "docs/RELEASE_CONTRACTS.md" "$RUNBOOK"
rg -q --fixed-strings "scripts/check_release_contracts.sh --docs-only" "$RUNBOOK"
rg -q --fixed-strings "scripts/release_validate.sh --ci --require-clean" "$RUNBOOK"
rg -q --fixed-strings "scripts/check_release_validate_ci.sh" "$RUNBOOK"

echo "release contracts doc checks passed"
